version: '3'
services:
  receiver-web-server:
    build: ./receiver-web-server
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - receiver-web-app

  talkative-web-server:
    build: ./talkative-web-server
    ports:
      - "8000:80"
    depends_on:
      - talkative-web-app

  receiver-web-app:
    depends_on:
      - message-broker
    build: ./receiver-web-app
    working_dir: /src
    volumes:
      - ./receiver-web-app/src:/src/
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
    expose:
      - "5000"

  talkative-web-app:
    depends_on:
      - message-broker
    build: ./talkative-web-app
    working_dir: /src
    volumes:
      - ./talkative-web-app/src:/src/
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    command: python main.py
    expose:
      - "5001"

  message-broker:
    hostname: message-host
    image: rabbitmq:3.6.9
    expose:
      - "5672"
