#!/usr/bin/env bash
set -e

usage() {
    echo -e "SOA messenger homework assignment:\n \
    up - start up services\n \
    down - stop services"
    exit 1
}

case $1 in
up)
    docker-compose up -d --build
;;
down)
    docker-compose stop
;;
*)
    usage
;;
esac